#!/usr/bin/env bash
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/pi-dotfiles-content-test.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT HUP INT TERM

fail() { echo "FAIL: $*" >&2; exit 1; }
contains() { grep -Fq "$2" "$1" || fail "expected '$2' in $1"; }
not_contains() { grep -Fq "$2" "$1" && fail "did not expect '$2' in $1" || true; }
run_helper() { HOME="$1" bash "$2/sync-agent-content.sh" "${@:3}"; }
expect_failure() {
  home="$1" repo="$2"; shift 2
  if HOME="$home" bash "$repo/sync-agent-content.sh" "$@" >"$WORK/output" 2>&1; then
    fail "expected failure: $*"
  fi
}
new_repo() {
  target="$1"
  mkdir -p "$target"
  cp -R "$ROOT/home" "$target/home"
  cp "$ROOT/sync-agent-content.sh" "$target/sync-agent-content.sh"
}

# Fresh deployment: shared skills land once in .agents, Claude links to them,
# and Pi-only skills stay out of both other clients.
repo="$WORK/fresh-repo"
home="$WORK/fresh-home"
new_repo "$repo"
mkdir -p "$home/.claude" "$home/.codex" "$home/.claude/skills/gstack" \
  "$home/.claude/skills/synced" "$home/.codex/skills/external-codex" \
  "$home/.agents/skills/simplify" "$home/.agents/skills/use-tinyfish" \
  "$home/.pi/agent/skills/foreign-pi" "$home/.config/pi-dotfiles/local" \
  "$home/third-party/gstack"
ln -s "$home/third-party/gstack" "$home/.codex/skills/gstack"
printf 'keep Codex gstack link\n' > "$home/third-party/gstack/KEEP"
printf 'keep gstack\n' > "$home/.claude/skills/gstack/KEEP"
printf 'keep synced\n' > "$home/.claude/skills/synced/KEEP"
printf 'keep codex\n' > "$home/.codex/skills/external-codex/KEEP"
printf 'keep Vercel\n' > "$home/.agents/skills/simplify/SKILL.md"
printf 'keep TinyFish\n' > "$home/.agents/skills/use-tinyfish/SKILL.md"
printf 'keep foreign Pi\n' > "$home/.pi/agent/skills/foreign-pi/KEEP"
printf 'local overlay survives\n' > "$home/.config/pi-dotfiles/local/pi.md"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "fresh deployment"; }
[ -f "$home/.agents/skills/bro/SKILL.md" ] || fail "shared bro missing"
[ -f "$home/.agents/skills/tdd/SKILL.md" ] || fail "shared tdd missing"
cmp "$repo/home/shared-skills/bro/SKILL.md" "$home/.agents/skills/bro/SKILL.md" || fail "bro source changed"
cmp "$repo/home/shared-skills/bro/LICENSE" "$home/.agents/skills/bro/LICENSE" || fail "bro license changed"
[ -L "$home/.claude/skills/tdd" ] || fail "Claude tdd path is not a symlink"
[ "$(readlink "$home/.claude/skills/tdd")" = "$home/.agents/skills/tdd" ] || fail "Claude link target is wrong"
[ -f "$home/.pi/agent/skills/personal-workflow/SKILL.md" ] || fail "Pi-only skill missing from Pi"
[ ! -e "$home/.agents/skills/personal-workflow" ] || fail "Pi-only skill leaked into shared root"
[ ! -e "$home/.claude/skills/personal-workflow" ] || fail "Pi-only skill leaked into Claude"
[ ! -e "$home/.codex/skills/personal-workflow" ] || fail "Pi-only skill leaked into Codex"
[ -f "$home/.agents/skills/simplify/SKILL.md" ] || fail "unmanaged shared skill was removed"
[ -f "$home/.agents/skills/use-tinyfish/SKILL.md" ] || fail "unmanaged TinyFish skill was removed"
[ -f "$home/.claude/skills/gstack/KEEP" ] || fail "gstack was modified"
[ -f "$home/.claude/skills/synced/KEEP" ] || fail "Claude synced/ was modified"
[ -f "$home/.codex/skills/external-codex/KEEP" ] || fail "Codex native skill was modified"
[ -L "$home/.codex/skills/gstack" ] || fail "Codex gstack symlink was modified"
[ "$(readlink "$home/.codex/skills/gstack")" = "$home/third-party/gstack" ] || fail "Codex gstack symlink target changed"
contains "$home/third-party/gstack/KEEP" 'keep Codex gstack link'
[ -f "$home/.pi/agent/skills/foreign-pi/KEEP" ] || fail "foreign Pi skill was modified"
contains "$home/.pi/agent/AGENTS.md" 'local overlay survives'
contains "$home/.codex/AGENTS.md" 'Match my writing style:'
contains "$home/.codex/AGENTS.md" '<!-- context7 -->'
contains "$home/.claude/CLAUDE.md" 'Generated by pi-dotfiles'

# Shared source edits flow to all clients through the canonical .agents copy/link.
printf '\n# test update\n' >> "$repo/home/shared-skills/tdd/SKILL.md"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "shared skill update"; }
contains "$home/.agents/skills/tdd/SKILL.md" '# test update'
contains "$home/.claude/skills/tdd/SKILL.md" '# test update'

# Pruning removes only helper-managed paths, not unrelated or Vercel-owned skills.
rm -rf "$repo/home/shared-skills/tdd"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "managed prune"; }
[ ! -e "$home/.agents/skills/tdd" ] || fail "removed managed skill remains in .agents"
[ ! -e "$home/.claude/skills/tdd" ] || fail "removed managed Claude link remains"
[ -f "$home/.agents/skills/simplify/SKILL.md" ] || fail "prune removed unmanaged skill"
[ -f "$home/.claude/skills/gstack/KEEP" ] || fail "prune touched gstack"

# No Codex or Claude directory is created on a machine without those clients.
repo="$WORK/no-cli-repo"
home="$WORK/no-cli-home"
new_repo "$repo"
mkdir -p "$home"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "no-CLI deployment"; }
[ ! -e "$home/.codex" ] || fail "created absent Codex directory"
[ ! -e "$home/.claude" ] || fail "created absent Claude directory"
[ -f "$home/.pi/agent/AGENTS.md" ] || fail "Pi instruction target missing"

# Same-name unmanaged shared collisions fail before modifying any destination.
repo="$WORK/collision-repo"
home="$WORK/collision-home"
new_repo "$repo"
mkdir -p "$home/.agents/skills/bro" "$home/.pi/agent/skills/personal-workflow"
printf 'user-owned\n' > "$home/.agents/skills/bro/SKILL.md"
printf 'legacy repo-owned\n' > "$home/.pi/agent/skills/personal-workflow/SKILL.md"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'unmanaged collision for bro'
contains "$WORK/output" "$home/.agents/skills/bro"
contains "$WORK/output" 'no approved copy action'
contains "$WORK/output" 'rerun with --adopt to approve copy'
not_contains "$WORK/output" "approved $home/.agents/skills/bro action"
contains "$home/.agents/skills/bro/SKILL.md" 'user-owned'
[ ! -e "$home/.agents/skills/tdd" ] || fail "collision preflight partially deployed skills"

# A same-name symlink in the shared root is also an unmanaged collision; never follow or replace it.
repo="$WORK/symlink-collision-repo"
home="$WORK/symlink-collision-home"
new_repo "$repo"
mkdir -p "$home/.agents/skills" "$home/user-owned/bro"
printf 'user-owned symlink target\n' > "$home/user-owned/bro/SKILL.md"
ln -s "$home/user-owned/bro" "$home/.agents/skills/bro"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'unmanaged collision for bro'
[ -L "$home/.agents/skills/bro" ] || fail "unmanaged skill symlink was replaced"
[ "$(readlink "$home/.agents/skills/bro")" = "$home/user-owned/bro" ] || fail "unmanaged skill symlink target changed"
contains "$home/user-owned/bro/SKILL.md" 'user-owned symlink target'
[ ! -e "$home/.agents/skills/tdd" ] || fail "symlink collision preflight partially deployed skills"

# Claude collisions name the exact link-replacement action rather than an absolute path.
repo="$WORK/claude-collision-repo"
home="$WORK/claude-collision-home"
new_repo "$repo"
mkdir -p "$home/.claude/skills/bro"
printf 'user-owned Claude copy\n' > "$home/.claude/skills/bro/SKILL.md"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'unmanaged collision for bro'
contains "$WORK/output" 'no approved replace-claude-copy-with-link action'
not_contains "$WORK/output" "approved $home/.claude/skills/bro action"
contains "$home/.claude/skills/bro/SKILL.md" 'user-owned Claude copy'
[ ! -e "$home/.agents/skills/tdd" ] || fail "Claude collision preflight partially deployed skills"

# A normal rebuild never claims or deletes an unmanaged same-name old Pi copy.
repo="$WORK/old-pi-repo"
home="$WORK/old-pi-home"
new_repo "$repo"
mkdir -p "$home/.pi/agent/skills/bro"
printf 'unmanaged old Pi copy\n' > "$home/.pi/agent/skills/bro/SKILL.md"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'unmanaged old Pi copy for bro'
[ -f "$home/.pi/agent/skills/bro/SKILL.md" ] || fail "normal run deleted unmanaged Pi copy"
[ ! -e "$home/.agents/skills/bro" ] || fail "normal run partially deployed shared skill"

# Adoption is path/action allowlisted, dry-run first, and backs up changed copies.
repo="$WORK/adopt-repo"
home="$WORK/adopt-home"
new_repo "$repo"
mkdir -p "$home/.pi/agent/skills/personal-workflow" "$home/.pi/agent/skills/equity-modelling" \
  "$home/.pi/agent/skills/bro" "$home/.claude/skills/grilling" \
  "$home/.claude/skills/gstack" "$home/.codex/skills/gstack"
cp -R "$repo/home/skills/personal-workflow/." "$home/.pi/agent/skills/personal-workflow/"
cp -R "$repo/home/skills/equity-modelling/." "$home/.pi/agent/skills/equity-modelling/"
printf 'local legacy difference\n' > "$home/.pi/agent/skills/equity-modelling/legacy.txt"
cp -R "$repo/home/shared-skills/bro/." "$home/.pi/agent/skills/bro/"
printf 'old Pi-only material\n' > "$home/.pi/agent/skills/bro/old-version.txt"
printf 'old Claude copy\n' > "$home/.claude/skills/grilling/claude-only.txt"
printf 'keep gstack\n' > "$home/.claude/skills/gstack/KEEP"
printf 'keep codex gstack\n' > "$home/.codex/skills/gstack/KEEP"
printf 'personalized codex policy\n' > "$home/.codex/AGENTS.md"
inode_before="$(python3 -c 'import os,sys; print(os.stat(sys.argv[1]).st_ino)' "$home/.pi/agent/skills/personal-workflow/SKILL.md")"
HOME="$home" bash "$repo/sync-agent-content.sh" --adopt > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "adoption dry run"; }
contains "$WORK/output" 'ADOPT identical directory without replacing'
contains "$WORK/output" 'old-version.txt'
[ ! -e "$home/.local/state/pi-dotfiles/managed-paths" ] || fail "--adopt without --yes wrote the manifest"
[ -f "$home/.pi/agent/skills/bro/old-version.txt" ] || fail "--adopt without --yes removed the old Pi copy"
[ -f "$home/.codex/AGENTS.md" ] && contains "$home/.codex/AGENTS.md" 'personalized codex policy'
inode_after="$(python3 -c 'import os,sys; print(os.stat(sys.argv[1]).st_ino)' "$home/.pi/agent/skills/personal-workflow/SKILL.md")"
[ "$inode_before" = "$inode_after" ] || fail "dry-run changed an identical allowlisted copy"

HOME="$home" bash "$repo/sync-agent-content.sh" --adopt --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "approved adoption"; }
[ -f "$home/.agents/skills/bro/SKILL.md" ] || fail "shared copy was not deployed before pruning"
[ ! -e "$home/.pi/agent/skills/bro" ] || fail "allowlisted stale Pi copy remains"
[ -L "$home/.claude/skills/grilling" ] || fail "Claude copy was not replaced by a managed link"
[ -f "$home/.claude/skills/gstack/KEEP" ] || fail "adoption touched unmanaged Claude skill"
[ -f "$home/.codex/skills/gstack/KEEP" ] || fail "adoption touched unmanaged Codex skill"
[ -f "$home/.pi/agent/skills/equity-modelling/SKILL.md" ] || fail "Pi-only source was not deployed"
[ ! -e "$home/.pi/agent/skills/equity-modelling/legacy.txt" ] || fail "differing Pi-only copy was not replaced"
[ -f "$home/.codex/AGENTS.md" ] || fail "Codex instructions were not generated"
contains "$home/.codex/AGENTS.md" 'Match my writing style:'
contains "$home/.codex/AGENTS.md" '<!-- context7 -->'
backup_root="$home/.local/state/pi-dotfiles/backups"
[ -d "$backup_root" ] || fail "adoption backups missing"
[ -n "$(find "$backup_root" -name legacy.txt -print -quit)" ] || fail "differing Pi-only copy was not backed up"
[ -n "$(find "$backup_root" -name old-version.txt -print -quit)" ] || fail "old shared Pi copy was not backed up"
[ -n "$(find "$backup_root" -name 'claude-only.txt' -print -quit)" ] || fail "Claude copy backup missing"

# If upstream show-me was not installed, the old unmanaged Pi copy is preserved.
mkdir -p "$home/.pi/agent/skills/show-me"
printf 'old show-me\n' > "$home/.pi/agent/skills/show-me/SKILL.md"
HOME="$home" bash "$repo/sync-agent-content.sh" --adopt --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "post-adoption run"; }
[ -f "$home/.pi/agent/skills/show-me/SKILL.md" ] || fail "show-me removed without upstream replacement"
mkdir -p "$home/.agents/skills/show-me"
printf 'synthetic upstream show-me\n' > "$home/.agents/skills/show-me/SKILL.md"
HOME="$home" bash "$repo/sync-agent-content.sh" --adopt --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "show-me upstream migration"; }
[ ! -e "$home/.pi/agent/skills/show-me" ] || fail "show-me Pi copy remains after upstream install"
[ -n "$(grep -R -l -F 'old show-me' "$home/.local/state/pi-dotfiles/backups")" ] || fail "old show-me copy was not backed up"
[ -f "$home/.agents/skills/show-me/SKILL.md" ] || fail "upstream show-me copy was touched"

# The allowlist rejects a new same-name collision even with --adopt.
mkdir -p "$repo/home/shared-skills/new-unapproved" "$home/.agents/skills/new-unapproved"
printf '%s\n' '---' 'name: new-unapproved' 'description: test' '---' > "$repo/home/shared-skills/new-unapproved/SKILL.md"
printf 'unmanaged\n' > "$home/.agents/skills/new-unapproved/SKILL.md"
expect_failure "$home" "$repo" --adopt --yes
contains "$WORK/output" 'unmanaged collision for new-unapproved'
contains "$home/.agents/skills/new-unapproved/SKILL.md" 'unmanaged'

# Losing the manifest causes no pruning and turns existing targets into collisions.
repo="$WORK/lost-manifest-repo"
home="$WORK/lost-manifest-home"
new_repo "$repo"
mkdir -p "$home/.claude"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "initial lost-manifest deployment"; }
rm "$home/.local/state/pi-dotfiles/managed-paths"
rm -rf "$repo/home/shared-skills/bro"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'No ownership manifest: prune nothing'
contains "$WORK/output" 'unmanaged collision for tdd'
[ -f "$home/.agents/skills/tdd/SKILL.md" ] || fail "missing manifest allowed deletion"
[ -f "$home/.agents/skills/bro/SKILL.md" ] || fail "missing manifest pruned a former managed skill"

# Generated-instruction drift is backed up and stopped; --force backs up then proceeds.
repo="$WORK/drift-repo"
home="$WORK/drift-home"
new_repo "$repo"
mkdir -p "$home/.config/pi-dotfiles/local"
printf 'machine overlay\n' > "$home/.config/pi-dotfiles/local/pi.md"
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "initial instruction generation"; }
printf '\nhand edit\n' >> "$home/.pi/agent/AGENTS.md"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'generated instructions changed since last run'
contains "$home/.pi/agent/AGENTS.md" 'hand edit'
[ -n "$(find "$home/.local/state/pi-dotfiles/backups" -type f -print -quit)" ] || fail "drift backup missing"
backup_count_before="$(find "$home/.local/state/pi-dotfiles/backups" -type f | wc -l | tr -d ' ')"
HOME="$home" bash "$repo/sync-agent-content.sh" --force --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "forced instruction generation"; }
contains "$home/.pi/agent/AGENTS.md" 'machine overlay'
not_contains "$home/.pi/agent/AGENTS.md" 'hand edit'
HOME="$home" bash "$repo/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "instruction regeneration"; }
backup_count_after="$(find "$home/.local/state/pi-dotfiles/backups" -type f | wc -l | tr -d ' ')"
[ "$backup_count_after" -ge "$backup_count_before" ] || fail "a later run deleted backups"

# First-run Codex content is backed up and left alone without --adopt.
repo="$WORK/codex-first-run-repo"
home="$WORK/codex-first-run-home"
new_repo "$repo"
mkdir -p "$home/.codex"
printf 'codex-local-content\n' > "$home/.codex/AGENTS.md"
expect_failure "$home" "$repo" --yes
contains "$WORK/output" 'first-run instructions contain local content'
contains "$home/.codex/AGENTS.md" 'codex-local-content'
[ -n "$(find "$home/.local/state/pi-dotfiles/backups" -type f -print -quit)" ] || fail "first-run Codex content was not backed up"

# Exercise the VPS staging shape: rsync --delete only touches a temporary stage,
# then the same helper preserves foreign entries in both native skill roots.
repo="$WORK/vps-source"
home="$WORK/vps-home"
stage="$WORK/vps-stage"
new_repo "$repo"
mkdir -p "$stage" "$home/.agents/skills/vps-foreign" "$home/.pi/agent/skills/vps-foreign"
printf 'keep shared foreign\n' > "$home/.agents/skills/vps-foreign/KEEP"
printf 'keep Pi foreign\n' > "$home/.pi/agent/skills/vps-foreign/KEEP"
rsync -a --delete "$repo/" "$stage/"
HOME="$home" bash "$stage/sync-agent-content.sh" --yes > "$WORK/output" 2>&1 || { cat "$WORK/output"; fail "staged VPS helper"; }
contains "$home/.agents/skills/vps-foreign/KEEP" 'keep shared foreign'
contains "$home/.pi/agent/skills/vps-foreign/KEEP" 'keep Pi foreign'

# Pin the upstream import and license as well as the commit recorded in attribution.
skill_hash="$(shasum -a 256 "$ROOT/home/shared-skills/bro/SKILL.md" | awk '{print $1}')"
license_hash="$(shasum -a 256 "$ROOT/home/shared-skills/bro/LICENSE" | awk '{print $1}')"
[ "$skill_hash" = '577525d7959c56786afe19f35d1bd54f6b5e53aacad4910d1fc9669e7ef2a1d0' ] || fail "bro SKILL.md differs from imported upstream revision"
[ "$license_hash" = 'd8fb8acb7a55ecffe2addab2634ebde374621eec5f7c2e065a4d5b740d474611' ] || fail "bro LICENSE differs from upstream"
contains "$ROOT/home/skills/ATTRIBUTION.md" '3aa8c40b1241111f73ab5360e770f7512193a20e'

"$ROOT/lint-agent-content.sh"
echo 'sync-agent-content tests passed.'
